/** Generated from Figma. Mapped references Alias only — no raw values. */
import { alias } from "./alias";
import type { MappedTokens } from "./types";

export const mapped: MappedTokens = {
  light: {
    Text: {
      headings: alias["Neutral"]["800"],
      body: alias["Neutral"]["700"],
      placeholder: alias["Neutral"]["400"],
      action: alias["Primary"]["default-fixed"],
      "action-hover": alias["Primary"]["600"],
      disabled: alias["Neutral"]["Default"],
      information: alias["Information"]["500"],
      warning: alias["Warning"]["Default"],
      success: alias["Success"]["500"],
      error: alias["Error"]["default"],
      "on-action": alias["Neutral"]["white"],
    },
    Icon: {
      default: alias["Neutral"]["700"],
      action: alias["Primary"]["default-fixed"],
      "action-hover": alias["Primary"]["600"],
      disabled: alias["Neutral"]["Default"],
      information: alias["Information"]["500"],
      warning: alias["Warning"]["Default"],
      success: alias["Success"]["500"],
      error: alias["Error"]["default"],
      "on-action": alias["Neutral"]["white"],
    },
    Surface: {
      page: alias["Neutral"]["white"],
      default: alias["Neutral"]["white"],
      action: alias["Primary"]["default-fixed"],
      "action-hover": alias["Primary"]["600"],
      "action-hover-light": alias["Primary"]["50"],
      success: alias["Success"]["50"],
      warning: alias["Warning"]["50"],
      information: alias["Information"]["50"],
      error: alias["Error"]["50"],
      disabled: alias["Neutral"]["100"],
    },
    Border: {
      default: alias["Neutral"]["50"],
      "default-2": alias["Neutral"]["50"],
      success: alias["Success"]["200"],
      information: alias["Information"]["200"],
      warning: alias["Warning"]["200"],
      error: alias["Error"]["50"],
      action: alias["Primary"]["default-fixed"],
      "action-hover": alias["Primary"]["600"],
      focus: alias["Primary"]["default-fixed"],
      disabled: alias["Neutral"]["100"],
      "disabled-2": alias["Neutral"]["100"],
    },
  },
  dark: {
    Text: {
      headings: alias["Neutral"]["50"],
      body: alias["Neutral"]["50"],
      placeholder: alias["Neutral"]["400"],
      action: alias["Primary"]["default-fixed"],
      "action-hover": alias["Primary"]["400"],
      disabled: alias["Neutral"]["300"],
      information: alias["Information"]["400"],
      warning: alias["Warning"]["400"],
      success: alias["Success"]["400"],
      error: alias["Error"]["400"],
      "on-action": alias["Neutral"]["black"],
    },
    Icon: {
      default: alias["Neutral"]["200"],
      action: alias["Primary"]["default-fixed"],
      "action-hover": alias["Primary"]["600"],
      disabled: alias["Neutral"]["300"],
      information: alias["Information"]["400"],
      warning: alias["Warning"]["400"],
      success: alias["Success"]["400"],
      error: alias["Error"]["400"],
      "on-action": alias["Neutral"]["black"],
    },
    Surface: {
      page: alias["Neutral"]["black"],
      default: alias["Neutral"]["black"],
      action: alias["Primary"]["default-fixed"],
      "action-hover": alias["Primary"]["400"],
      "action-hover-light": alias["Primary"]["800"],
      success: alias["Success"]["800"],
      warning: alias["Warning"]["800"],
      information: alias["Information"]["800"],
      error: alias["Error"]["800"],
      disabled: alias["Neutral"]["400"],
    },
    Border: {
      default: alias["Neutral"]["Default"],
      "default-2": alias["Neutral"]["50"],
      information: alias["Information"]["600"],
      warning: alias["Warning"]["600"],
      error: alias["Error"]["600"],
      action: alias["Primary"]["default-fixed"],
      "action-hover": alias["Primary"]["600"],
      focus: alias["Primary"]["default-fixed"],
      disabled: alias["Neutral"]["800"],
      "disabled-2": alias["Neutral"]["400"],
    },
  },
} as MappedTokens;
